"""add_deleted_at_to_document

Revision ID: 8d7e30d4faa1
Revises: ace658e79e10
Create Date: 2026-07-07 01:44:20.062220
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d7e30d4faa1'
down_revision: str | None = 'ace658e79e10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
